customing_app/urls.py
from django.urls import path
import customing_app.views as views
import customing_app.rest as rest

urlpatterns = [
    path('', views.home),
    path('links/', views.links),
    path('design/', views.colors),

    path('design/test/', views.link_test),
    path('design/fonts/', views.fonts_page),
    
    path('stats/', views.statistics),

    path('links/edit/', rest.edit_link_name),
    path('links/new/', rest.create_link),
    path('links/delete/', rest.delete_link),
    path('links/edit/pos/', rest.edit_pos),
    
    path('create/', rest.create_profile),
    path('design/create/', rest.create_scheme),
    path('design/change/color/', rest.change_color),
    path('design/change/font/', rest.change_font),
    path('design/change/font_type/', rest.change_font_type),
    path('design/change/button/', rest.change_button),
    path('design/change/shape/', rest.change_shape),

    path('new/font/', rest.get_new_font),
    

    path('change/', rest.edit_profile),
    path('image/', rest.upload_image),
    path('image/delete/', rest.delete_image),
]

link/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('customing_app.urls')),
    path('', include('welcome_app.urls')),
    path('l/', include('show_app.urls')),
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#! WELCOME -- login, register, logout, landing
#! CUSTOMISING -- info, links, color theme, delete
#! SHOW -- /l/ -- links

customing_app/models.py
from django.db import models
import re

LINK_REGEX = r'^[A-Za-z0-9_-]+\.[a-zA-Z]'
COLOR_REGEX = r'^#[A-Fa-f0-9]{6}$'
RADIUSES = ('0', '.5', '1.5',)
AVA_RADIUSES = ('0', '10', '25', '50')
ADDITIONAL_CSS_BTNS = (
    '',
    r'background:transparent;outline:{OUTLINE} 2px solid;',
    r'box-shadow: 0px 3px 6px rgba({SHADOW_RGB}, 0.15);',
    r'box-shadow: 5px 5px 0px {SHADOW};transition-duration: 0s;}.button:hover {transform: translate(2px, 2px);box-shadow: 3px 3px 0px {SHADOW}' #outline:{OUTLINE} 2px solid;
)
BTN_BASE = r'.button:hover{transform: scale(1.05);}.button{background:{BTN};color:{BTN_FONT};font-weight:600;padding:.75rem 1rem;border-radius:{RADIUS}rem;cursor:pointer;display:flex;justify-content:center;align-items:center;box-sizing:border-box;transition:transform .15s ease-out;border-color:transparent;text-decoration:none;margin-bottom:1rem;{ADDITIONAL}}'
class Profile(models.Model):
    name = models.CharField(max_length=100)
    about = models.CharField(max_length=400)
    owner = models.ForeignKey('welcome_app.User', on_delete=models.CASCADE,)

    image = models.ImageField(upload_to='media', null=True)
    colors = models.ForeignKey('customing_app.ColorScheme', on_delete=models.CASCADE, blank=True, null=True)
    #TODO: статистика

    def __str__(self) -> str:
        return self.name

    def short_body(self) -> str:
        if len(self.about) > 200:
            return f'{self.about[:450]}...'
        return self.about
    
    def get_links(self):
        return Link.objects.filter(user_profile=self)
    

    class Meta:
        db_table = 'Profiles'
        verbose_name = 'профиль'
        verbose_name_plural = 'профили'


class Link(models.Model):
    icon = models.CharField(max_length=100, default='link', verbose_name='иконка')
    url = models.CharField(max_length=400, verbose_name='ссылка')
    user_profile = models.ForeignKey('customing_app.Profile', on_delete=models.CASCADE, verbose_name='профиль')
    title = models.CharField(max_length=100, verbose_name='заголовок')
    position = models.IntegerField(verbose_name='позиция', null=True)

    def __str__(self) -> str:
        return self.title

    def save(self, *args, **kwargs):
        if self.position is None:
            self.position = Link.objects.filter(user_profile=self.user_profile).count()
        super().save(*args, **kwargs)
        
    class Meta:
        db_table = 'Links'
        verbose_name = 'ссылку'
        verbose_name_plural = 'ссылки'


class ColorScheme(models.Model):
    owner = models.ForeignKey('customing_app.Profile', on_delete=models.CASCADE, blank=True, null=True)

    # card = models.CharField(max_length=8, default='#15151E', verbose_name='card')
    
    avatar_shape = models.IntegerField(default=3) #1-4
    button_shape = models.IntegerField(default=1) #1-3
    button_type = models.IntegerField(default=1) # 1-4
    
    button_font = models.CharField(max_length=8, default='#D0EEFF', verbose_name='button font')
    background = models.CharField(max_length=8, default='#172C38', verbose_name='background')
    font = models.CharField(max_length=8, default='#FFFFFF', verbose_name='font')
    button = models.CharField(max_length=8, default='#172C38', verbose_name='button')
    outline = models.CharField(max_length=8, default='#172C38', verbose_name='outline')
    shadow = models.CharField(max_length=8, default='#FFFFFF', verbose_name='shadow')

    font_name = models.ForeignKey('customing_app.Font', on_delete=models.CASCADE, blank=True, null=True)



    class Meta:
        db_table = 'ColorScheme'
        verbose_name = 'цветовую схему'
        verbose_name_plural = 'цветовые схемы'
    
    def __str__(self) -> str:
        return f'Схема {self.owner.name}'
    
    def set_color(self, color_id:str, color_hash:str):
        if self.check_color(color_hash):
            color_id = color_id.replace('-color-input', '')
            match color_id:
                case "shadow":
                    self.shadow = color_hash
                case "button":
                    self.button = color_hash
                case "outline":
                    self.outline = color_hash
                case "button-text":
                    self.button_font = color_hash
                case "font":
                    self.font = color_hash
                case "background":
                    self.background = color_hash
                case _:
                    return False
            self.save()
            return True
        return False
            
    def set_font(self, font):
        font_id = int(font.split('_')[1])
        font = Font.objects.filter(id=font_id).first()
        if font is not None:
            self.font_name = font
            self.save()
            return True
        return False

    def get_button_css(self) -> str:
        baza = BTN_BASE.replace(r'{ADDITIONAL}', ADDITIONAL_CSS_BTNS[self.button_type-1])
        baza = baza.replace(r'{BTN}', self.button)
        baza = baza.replace(r'{BTN_FONT}', self.button_font)
        baza = baza.replace(r'{SHADOW}', self.shadow)
        baza = baza.replace(r'{OUTLINE}', self.outline)
        baza = baza.replace(r'{RADIUS}', RADIUSES[self.button_shape-1])
        if self.button_type == 3:
            baza = baza.replace(r'{SHADOW_RGB}', hex_to_rgb(self.shadow))
        return baza

    def get_ava_radius(self) -> str:
        return AVA_RADIUSES[self.avatar_shape]

    def get_font(self):
        if self.font_name is not None:
            return self.font_name.gfont()
        return Font.objects.first().gfont()
    
    def name_font(self):
        if self.font_name is not None:
            return self.font_name.name
        return Font.objects.first().name
    
    def img_font(self):
        if self.font_name is not None:
            return self.font_name.img_name
        return Font.objects.first().img_name

    def check_color(self, color: str) -> bool:
        is_ok = re.search(COLOR_REGEX, color)
        if is_ok is None:
            return False
        return True

class Font(models.Model):
    name = models.CharField(max_length=40, verbose_name='Название шрифта')
    img_name = models.CharField(max_length=40, verbose_name='картинка')

    def __str__(self) -> str:
        return f'Шрифт {self.name}'
    
    def as_json(self) -> tuple:
        return [self.id, self.name, self.img_name]
    
    def gfont(self):
        return self.name.title().replace(' ', '+')

    class Meta:
        db_table = 'Fonts'
        verbose_name = 'шрифт'
        verbose_name_plural = 'шрифты'


def add_fonts():
    "Создаёт модели шрифтов, запускать если их нет"
    with open("font_pic_generator/font_list.txt", "r") as file:
        font_list = file.read().splitlines()
    for font in font_list:
        new_font = Font()
        new_font.name = font.title()
        new_font.img_name = font.replace(' ', "_")
        new_font.save()


def get_fonts():
    unsorted = tuple(font.as_json() for font in Font.objects.all())
    return tuple(unsorted[i:i+2] for i in range(0, len(unsorted), 2))


def hex_to_rgb(hex_code:str):
    hex_code = hex_code.lstrip('#')
    return str(tuple(int(hex_code[i:i+2], 16) for i in (0, 2, 4)))[1:-1]


def check_link_correct(link:str) -> bool:
    #TODO: перенести в более подходящее место
    link = link.replace('http://', '').replace('https://', '')
    is_ok = re.search(LINK_REGEX, link)
    if is_ok is None:
        return False
    return True

customing_app/forms.py
from django import forms


class ProfileForm(forms.Form):
    name = forms.CharField(max_length=100)
    about = forms.CharField(max_length=400, required=False)


class LinkEditForm(forms.Form):
    id = forms.IntegerField()
    url = forms.CharField()
    title = forms.CharField()


class LinkPosForm(forms.Form):
    id = forms.IntegerField()
    where = forms.IntegerField()


class NewLinkForm(forms.Form):
    url = forms.CharField()


class DeleteLinkForm(forms.Form):
    id = forms.IntegerField()


class ChangeColorForm(forms.Form):
    color_id = forms.CharField()
    color_hash = forms.CharField(max_length=8)


class ChangeButtonForm(forms.Form):
    button_id = forms.CharField(max_length=4)

class ChangeShapeForm(forms.Form):
    shape = forms.IntegerField()

class ChangeFontForm(forms.Form):
    font_name = forms.CharField(max_length=8)


class ProfilePicForm(forms.Form):
    avatar = forms.ImageField()
    
    class Meta:
        widgets = {
            'avatar': forms.ClearableFileInput(),
        }

customing_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings

from .models import Profile, Link, get_fonts
from .decorators import profile_required, scheme_required


@login_required
def home(request):
    profile = Profile.objects.filter(owner=request.user).first()
    return render(request, 'home.html', {'title': 'Настройка профиля', 'profile': profile, 'user': request.user})


@login_required
@scheme_required
def links(request):
    profile = Profile.objects.filter(owner=request.user).first()
    links = Link.objects.filter(user_profile=profile).order_by('position')

    return render(request, 'links.html', {'title': 'Изменение цвета', 'links': links, 'selected': 1})



@login_required
@profile_required
def colors(request):
    profile = Profile.objects.filter(owner=request.user).first()
    color_scheme = profile.colors
    return render(request, 'design.html', {'title': 'Настройка дизайна', 'scheme': color_scheme, 'selected': 2, 'profile': profile})


@login_required
@profile_required
def statistics(request):
    profile = Profile.objects.filter(owner=request.user).first()
    color_scheme = profile.colors
    return render(request, 'stats.html', {'title': 'Статистика профиля', 'scheme': color_scheme, 'selected': 3})

from show_app.views import link_show

@login_required
@scheme_required
def link_test(request):
    return link_show(request, request.user.username, True)


@login_required
@scheme_required
def fonts_page(request):
    user_font = Profile.objects.filter(owner=request.user).first().colors.font_name
    

    fonts = get_fonts()
    response = render(request, 'fonts_page.html', {'title': 'Статистика профиля', 'fonts': fonts, 'user_font': user_font})
    response['X-Frame-Options'] = 'ALLOWALL'
    return response

customing_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{ title }}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'styles/base.css' %}">
    </head>
    <body>
        {% block header %}
        {% endblock %}
        {% block content %}
        {% endblock %}
        {% block scripts %}
        {% endblock %}
    </body>
</html>

customing_app/templates/base_new.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name='language' content='RU'>
        <meta name='og:site_name' content='MYLink'>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{ title }}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;700;900&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'styles/base.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
        {% block styles %}
        {% endblock %}
    </head>
    <body>
        {% include 'header.html' %}
        {% block header %}
        {% endblock %}
        
        
        <main>
            {% block content %}
            {% endblock %}
        </main>

        {% block scripts %}
        {% endblock %}
    </body>
</html>

customing_app/templates/baza.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name='language' content='RU'>
        <meta name='og:site_name' content='MYLink'>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{ title }}</title>
        <link rel="stylesheet" href="{% static 'styles/base.css' %}">
        <link rel="stylesheet" href="https://unpkg.com/@tabler/icons@latest/iconfont/tabler-icons.min.css">
    </head>
    <body>
        {% block header %}
        {% endblock %}
        <div style="margin: 0;width: 100%;background-color: white;height: 2rem;position: fixed;left: 0;top: 0;z-index: 555;">
            <a href="/profile/">P</a>
            <a href="/profile/design/">C</a>
            <a href="/profile/links/">L</a>
            <a href="/logout" class="absolute-right">Выйти</a>
        </div>
        <style>
            html {
                color: #D0EEFF;
            }
        </style>
        
        <div class="page-content">
            {% block content %}
            {% endblock %}
        </div>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

customing_app/templates/colors.html
{% extends 'base_new.html' %}
{% load static %}

{% block content %}

{% if scheme == None %}

<h1 class="edit-heading">Ещё чуть-чуть</h1>
<div class="center-div">
    <div class="card">
        <h3>Выберите цветовую схему</h3>
        <a class="edit-link login-input" id="emp">
            <p class="edit-p">
                Стандартная
            </p>
        </a>
        <a class="edit-link login-input" id="own">
            <p class="edit-p">
                Моя собственная
            </p>
        </a>
    </div>
</div>
{% else %}
<h1>Дизайн</h1>
<div class="display-flex">
    {% for color in scheme.get_colors %}
    <div style="background-color: {{color}};" class="color-preview"></div>
    {% endfor %}
</div>


<p><a href="/profile/colors/edit" class="white-link">Изменить</a></p>
<p><a href="/profile/colors/test" class="white-link">Протестировать схему</a></p>
{% endif %}
{% endblock %}

{% block scripts %}
{% if scheme == None %}
<script src="{% static 'scripts/colors_welcome.js' %}"></script>
{% endif %}
{% endblock %}

customing_app/templates/design.html
{% extends 'base_new.html' %}
{% load static %}

{% block header %}

<!-- <div class="popup hid" id="font-popup">
    <div class="card">
        <i class="ti ti-x card-icon close-btn" onclick="javascript:close_popups()"></i>
        <div class="card">Аа СПИСОК ШРИФТОВ</div>
    </div>
</div> -->

<div id="popup" class="popup">
    <div class="card">
      <i class="ti ti-x card-icon close-btn" onclick="javascript:close_popup()"></i>
      <div class="card">Аа СПИСОК ШРИФТОВ</div>
    </div>
  </div>
<div class="popup-overlay"></div>

{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'styles/popup.css' %}">
{% endblock %}

{% block content %}

{% if scheme == None %}

<h1 class="edit-heading">Ещё чуть-чуть</h1>
<div class="center-div">
    <div class="card">
        <h3>Выберите цветовую схему</h3>
        <a class="edit-link login-input" id="emp">
            <p class="edit-p">
                Стандартная
            </p>
        </a>
        <a class="edit-link login-input" id="own">
            <p class="edit-p">
                Моя собственная
            </p>
        </a>
    </div>
</div>
{% else %}
<div class="outlined-selector" id="selector_1"></div>
<div class="outlined-selector" id="selector_2"></div>
<div class="card-list design-list">
    <h3>Профиль</h3>
    <div class="card">
        <div class="profile-top">
            <div class="ava-circle">
                <img id="profile-image" {% if profile.image %}src="{{ profile.image.url }}"{%else%}class="hid"{% endif %} style="position: absolute;width:0px;">
                <avaname {% if profile.image %}class="hid"{%endif%}>{{profile.name.0.upper}}</avaname>
            </div>
            <div class="buttons">
                <form id="ava-form">
                    <label for="avatar" class="button">Выбрать изображение</label>
                    <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg" class="hid">
                </form>
                <div class="button" id="avatar-delete">Удалить</div>
            </div>
        </div>
        <div class="profile-middle">
            <input type="text" placeholder="Имя" id="username" value="{{profile.name}}">
            <input type="text" placeholder="Описание" id="about" value="{{profile.about}}">
        </div>
        <h4>Скругление</h4>
        <div class="profile-bottom">
            <div class="d base-circling" id="avatar_1">1</div>
            <div class="d half-circling" id="avatar_2">2</div>
            <div class="d full-circling" id="avatar_3">3</div>
        </div>
    </div>


    <h3>Фон</h3>
    <div class="card">
        <!-- <div class="background-row">
            <div class="background-chose"></div>
            <div class="background-chose"></div>
            <div class="background-chose"></div>
            <div class="background-chose"></div>
        </div>
        <div class="background-row">
            <div class="background-chose"></div>
            <div class="background-chose"></div>
            <div class="background-chose"></div>
            <div class="background-chose"></div>
        </div> -->
        <h4 class="t">Цвет</h4>
        <div class="color-wrapper">
            <input type="color" class="colorsss" id="background-color-input" value="{{scheme.background}}">
            <div class="color-description">
                <h6>Цвет</h6>
                <div class="color" id="background-color-input-text">{{scheme.background}}</div>
            </div>
        </div>
    </div>

    <h3>Кнопки</h3>
    <div class="card">
        <h4 class="t">Заливка</h4>
        <div class="btn-row">
            <div class="s button btn-sample btn-sq" id="s1-1">&nbsp;</div>
            <div class="s button btn-sample btn-semi" id="s1-2">&nbsp;</div>
            <div class="s button btn-sample" id="s1-3">&nbsp;</div>
        </div>
        <h4>Обводка</h4>
        <div class="btn-row">
            <div class="s button btn-sq btn-outline" id="s2-1">&nbsp;</div>
            <div class="s button btn-semi btn-outline" id="s2-2">&nbsp;</div>
            <div class="s button btn-outline" id="s2-3">&nbsp;</div>
        </div>
        <h4>Мягкая тень</h4>
        <div class="btn-row">
            <div class="s button btn-sample btn-soft-shadow btn-sq" id="s3-1">&nbsp;</div>
            <div class="s button btn-sample btn-soft-shadow btn-semi" id="s3-2">&nbsp;</div>
            <div class="s button btn-sample btn-soft-shadow" id="s3-3">&nbsp;</div>
        </div>
        <h4>Жёсткая тень</h4>
        <div class="btn-row">
            <div class="s button btn-sample btn-outline btn-hard-shadow btn-sq" id="s4-1">&nbsp;</div>
            <div class="s button btn-sample btn-outline btn-hard-shadow btn-semi" id="s4-2">&nbsp;</div>
            <div class="s button btn-sample btn-outline btn-hard-shadow" id="s4-3">&nbsp;</div>
        </div>

        <h4>Цвет тени</h4>
        <div class="color-wrapper">
            <input type="color" class="colorsss" id="shadow-color-input" value="{{scheme.shadow}}">
            <label class="color-description" for="shadow-color-input">
                <h6>Цвет</h6>
                <div class="color" id="shadow-color-input-text">{{scheme.shadow}}</div>
            </label>
        </div>

        <h4>Цвет кнопки</h4>
        <div class="color-wrapper">
            <input type="color" class="colorsss" id="button-color-input" value="{{scheme.button}}">
            <label class="color-description" for="button-color-input">
                <h6>Цвет</h6>
                <div class="color" id="button-color-input-text">{{scheme.button}}</div>
            </label>
        </div>
        
        <h4>Обводка кнопки</h4>
        <div class="color-wrapper">
            <input type="color" class="colorsss" id="outline-color-input" value="{{scheme.outline}}">
            <label class="color-description" for="outline-color-input">
                <h6>Цвет</h6>
                <div class="color" id="outline-color-input-text">{{scheme.outline}}</div>
            </label>
        </div>


        <h4>Цвет текста</h4>
        <div class="color-wrapper">
            <input type="color" class="colorsss" id="button-text-color-input" value="{{scheme.button_font}}">
            <label class="color-description" for="button-text-color-input">
                <h6>Цвет</h6>
                <div class="color" id="button-text-color-input-text">{{scheme.button_font}}</div>
            </label>
        </div>
    </div>

    <h3>Шрифты</h3>
    <div class="card">
        <div class="color-popup-wrapper">
        <h4 class="t">Шрифт</h4>
            <div class="color-wrapper" id="color-wrapper">
                <img class="font-square" id="font-input-square" src="/media/fonts/{{scheme.img_font}}.webp">
                <div class="color-description font-text">
                    <h6>Шрифт</h6>
                    <div class="color" id="font-input-text">{{scheme.name_font}}</div>
                </div>
            </div>
            <div class="showable flex">
                <iframe src="/profile/design/fonts/"></iframe>
                <a class="button" id="new_font">OK</a>
            </div>
        </div>

        <h4>Цвет</h4>
        <div class="color-wrapper">
            <input type="color" class="colorsss" id="font-color-input" value="{{scheme.font}}">
            <label class="color-description" for="font-color-input">
                <h6>Цвет</h6>
                <div class="color" id="font-color-input-text">{{scheme.font}}</div>
            </label>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

{% block scripts %}
{% if scheme == None %}
<script src="{% static 'scripts/colors_welcome.js' %}"></script>
{% else %}
{% csrf_token %}
<script src="{% static 'scripts/preview_widget.js' %}"></script>
<script src="{% static 'scripts/colors_edit.js' %}"></script>
<script>
    changeButton(document.getElementById('s{{scheme.button_type}}-{{scheme.button_shape}}'), false);
    changeShape(document.getElementById('avatar_{{scheme.avatar_shape}}'), false);
    setTimeout(function () {document.querySelector('.showable').classList.remove('flex');document.querySelector('.showable').classList.add('hid')}, 700);
</script>

{% endif %}
{% endblock %}

customing_app/templates/fonts_page.html
{% load static %}
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- <link rel="stylesheet" href=""> -->
    </head>
    <body>
        <div class="outlined-selector" id="selector_font"></div>
        <link rel="stylesheet" href="{% static 'styles/fonts_style.css' %}">
        <div class="font-search"></div>
        <div class="font-table">
            {% for row in fonts %}
            <div class="font-row">
                {% for font in row %}
                    <div class="font" id="font_{{font.0}}">
                        <img class="font-image" src="/media/fonts/{{font.2}}.webp">
                        <div class="font-text">{{font.1}}</div>
                    </div>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
        {% csrf_token %}
        <script src="{% static 'scripts/fonts_page.js' %}"> </script>
        <script>
            {% if user_font != None %}
                setTimeout(function () {set_selector(document.getElementById('font_{{user_font.id}}', false))}, 200);
                
            {% endif %}
        </script>
    </body>
</html>

customing_app/templates/header.html
<header>
    <nav>
        <div class="desktop-only">
            <a class="item {% if selected == 1 %}nav-chosen{% endif %}" href="/profile/links/"><i class="ti ti-id"></i> Ссылки</a>
            <a class="item {% if selected == 2 %}nav-chosen{% endif %}" href="/profile/design/"><i class="ti ti-circle-square"></i> Дизайн</a>
            <a class="item {% if selected == 3 %}nav-chosen{% endif %}" href="/l/{{user.username}}"><i class="ti ti-chart-bar"></i> Моя страница</a>
            <!-- <a class="item {% if selected == 3 %}nav-chosen{% endif %}" href="/profile/stats/"><i class="ti ti-chart-bar"></i> Статистика</a> -->
        </div>
        <div class="desktop-only">
            <a class="item" href="/logout"><i class="ti ti-exit"></i><i class="ti ti-logout"></i> Выйти</a>
        </div>
        
    </nav>
</header>

customing_app/templates/home.html
{% extends 'base_new.html' %}

{% block content %}

{% if profile == None %}
    <h1 class="edit-heading">Пара моментов</h1>
    <div class="center-div">
        <div class="card">
            <h3>Чтобы продолжить, вам необходимо заполнить информацию о профиле</h4>
            <form id="create-profile">
                {% csrf_token %}
                <p>
                    <label for="id_username">Имя</label><br>
                    <input type="text" id="id_username" name="id_username" class="login-input" autocomplete="off" value="{{user.username}}">
                </p>
                <p>
                    <label for="id_about">Описание</label><br>
                    <input type="text" id="id_about" name="id_about" class="login-input" autocomplete="off">
                </p>
                <p class="button-group">
                    <button type="submit" class="button">Продолжить</button>
                </p>
            </form>
        </div>
    </div>
{% else %}
    <h1>Привет, {{user.username}}!</h1>
{% endif %}

{% endblock %}

{% block scripts %}
{% if profile == None %}
<script>
    document.getElementById('create-profile').addEventListener('submit', function(e) {
        e.preventDefault();
        username = document.getElementById('id_username').value;
        about = document.getElementById('id_about').value;

        if (username.replace(/\s/g, "") != "" ){
        fetch("/profile/create/", {
            method: "POST",
            body: JSON.stringify({
                    name: username,
                    about: about
                }),
            headers: {
                "Content-Type": "application/json",
                'X-CSRFToken': document.getElementsByName('csrfmiddlewaretoken')[0].value
            },
            })
        .then(data => {
            window.open('/profile/design', '_self');
        });}
});

</script>
{% endif %}
{% endblock %}